name: Update GitHub Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch and Update Stats
        run: |
          curl -L "https://github-readme-stats.vercel.app/api?username=Ritik0712-ai&show_icons=true&theme=radical&count_private=true&include_all_commits=true" > github-stats.png

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.png
          git commit -m "Updated GitHub Stats"
          git push
